### ISSUE TITLE
Easing when dragging?

### ISSUE THREAD

**Issue by fluxxus** [MasatoMakino/threejs-spherical-controls#150]
Hi! 

Is there an option to have some kind of easing/damping when dragging? 

Maybe I missed it, but I can't find anything related in the API docs. 

Thx

**Comment by MasatoMakino** [comment]
Hi @fluxxus,

Thanks for your question. In our module, the [EasingOption](https://masatomakino.github.io/threejs-spherical-controls/api/classes/EasingOption.html) in the API is specific to the [move](https://masatomakino.github.io/threejs-spherical-controls/api/classes/SphericalController.html#move) function within the SphericalController class. This function is designed to interpolate the camera movement between two coordinates, and it's not intended for interactive operations like dragging.

For implementing drag-related easing or damping, you might consider using a separate interaction handler. In this case, you can probably use the [SphericalController.addPosition](https://masatomakino.github.io/threejs-spherical-controls/api/classes/SphericalController.html#addPosition) function in your handler to adjust the camera position accordingly during interactive events.

Hope this helps!

**Comment by fluxxus** [comment]
@MasatoMakino thx for the quick reply!

Ok, I got you. I had a look at `SphericalController.addPosition`, I think I know how to implement the functionality I need.

I'll mark this as closed, appreciate the help and the explanation.
